package:
  name: blaze
  version: "0.6.6"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python
    - dynd-python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil

  run:
    - python
    - dynd-python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil

test:
  requires:
    - pytest
    - coverage

  commands:
    - python -c "import blaze; blaze.test()"

about:
  home: http://blaze.pydata.org
  license: BSD
